name: usage
description: Usage demonstration of Whixp.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

dependencies:
  whixp: ^2.1.1

dev_dependencies:
  lint: ^2.3.0
  test: ^1.24.0
